<H1>COMP216 Assignment 1</h1>

<h5> Please insert your name, student number, course and date </h5>


#Name: Jack

#Student number: 301220028

#Course: COMP 216

#Date: 2023-01-23



<h3>Instructions</h3>

We will continue working on python. Using a google colab notebook write the python statement to define a Pizza class. The test harness is provided to you by the instructor as well as the resulting output given.

<h4>How to do this assignment.</h4>
From the test harness and the given output, try to deduce the definition of the Pizza class. Code this class in a colab notebook and copy the test harness to a cell below. Execute the notebook and ensure that the output matches EXACTLY with the output on the following page.
You must use python f-strings for your output.

Do not modify the test harness.

<h4>Documentation.</h4>
Please enter your name and the current date somewhere at the top of your code.

<h4>How to submit this assignment.</h4>
Make the notebook shareable and submit the link to the course assessment folder.
See the folder documentation for due date.
See the course documentation for policy on deadlines.

In [87]:
# Jack
# 2023-01-26
class Pizza:
    sizes = {'small': 6.49, 'medium': 8.49, 'large': 10.49, 'x-large': 13.49 + 0.5}
    costPerTopping = 0.50
    
    @property
    def price(self):
        return self.sizes.get(self.__size) + len(self.__toppings) * self.costPerTopping
    
    @property
    def size(self):
        return self.__size
    @size.setter
    def size(self, value):
        if value not in self.sizes:
            raise ValueError(f'ERROR: {value} is not a valid size for a pizza ')
        else:
            self.__size = value
    
    def __init__(self, size = 'medium', toppings = ['cheese']):
        self.size = size
        self.__toppings = toppings
    
    def add(self, toppings):
        self.__toppings += toppings

    def __str__(self):
        return f"{self.size} pizza with {self.__toppings} for ${self.price}"



<h3>The test harness</h3>
You may not change the test harness.




 

In [88]:

print(f'Creating a default pizza')
p = Pizza()
print(p)

toppings = 'cheese olive'.split()
print(f'\nAdding topping: {toppings}')
p.add(toppings=toppings)
print(p)

print(f'\nCreating a new pizza')
p = Pizza('large', 'cheese pepper'.split())
print(p)

toppings = ['pineapple', 'mushroom']
print(f'\nAdding topping: {toppings}')
p.add(toppings)
print(p)

size = 'x-large'
p.size = size
print(f'\nChanging order size to {size}')
print(p)

size = 'gigantic'
print(f'\nChanging order size to {size}')
try:
  p.size = size
except ValueError as err:
  print(err) 


Creating a default pizza
medium pizza with ['cheese'] for $8.99

Adding topping: ['cheese', 'olive']
medium pizza with ['cheese', 'cheese', 'olive'] for $9.99

Creating a new pizza
large pizza with ['cheese', 'pepper'] for $11.49

Adding topping: ['pineapple', 'mushroom']
large pizza with ['cheese', 'pepper', 'pineapple', 'mushroom'] for $12.49

Changing order size to x-large
x-large pizza with ['cheese', 'pepper', 'pineapple', 'mushroom'] for $15.99

Changing order size to gigantic
ERROR: gigantic is not a valid size for a pizza 


<h4>The expected output</h4>

```
Creating a default pizza
medium pizza with ['cheese'] for $8.99

Adding topping: ['cheese', 'olive']
medium pizza with ['cheese', 'cheese', 'olive'] for $9.99

Creating a new pizza
large pizza with ['cheese', 'pepper'] for $11.49

Adding topping: ['pineapple']
large pizza with ['cheese', 'pepper', 'pineapple', 'mushroom'] for $12.49

Changing order size to x-large
x-large pizza with ['cheese', 'pepper', 'pineapple', 'mushroom'] for $15.99

Changing order size to gigantic
ERROR: gigantic is not a valid size for a pizza 
```